# Build Firmware Workflow

# This workflow builds the firmware for the Vial project
name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --break-system-packages -r requirements.txt

    - name: Build firmware
      run: |
        make all
